site_name: thunderfish

repo_url: https://github.com/bendalab/thunderfish/

edit_uri: ""

site_author: Benda-Lab

theme: readthedocs
    
nav:
    - Home: 'index.md'
    - 'User guide':
        - 'thunderfish': 'thunderfish.md'
        - 'collectfish': 'collectfish.md'
        - 'eodexplorer': 'eodexplorer.md'
    - 'Algorithms':
        - 'Pulse-fish EODs': 'pulses.md'
    - 'Code':
        - API reference: 'api/index.html'
