""" Files

Helper functions for parsing and reading files, generated by thunderfish.

## Functions

- `parse_filename()`: parse components of an EOD analysis file name.
- `open_from_zip()`: open file from corresponding zip file.
- `close_zip()`: close stream and corresponding zip file.

"""

import io

from pathlib import Path
from zipfile import ZipFile


def parse_filename(file_path):
    """Parse components of an EOD analysis file name.

    Analysis files generated by the `eodanalysis` module are named
    according to
    ```plain
    PATH/RECORDING-CHANNEL-TIME-FTYPE-N.EXT
    ```

    Parameters
    ----------
    file_path: str or Path
        Path of the file to be parsed.

    Returns
    -------
    recording: str
        Path and basename of the recording, i.e. 'PATH/RECORDING'.
        A leading './' is removed.
    base_path: Path
        Path and basename of the analysis results,
        i.e. 'PATH/RECORDING-CHANNEL-TIME'.
    channel: int
        Channel of the recording
        ('CHANNEL' component of the file name if present).
        -1 if not present in `file_path`.
    time: float
        Start time of analysis window in seconds
        ('TIME' component of the file name if present).
        `None` if not present in `file_path`.
    ftype: str
        Type of analysis file (e.g. 'wavespectrum', 'pulsephases', etc.),
        ('FTYPE' component of the file name if present).
        See `file_types` for a list of all supported file types.
        Empty string if not present in `file_path`.
    index: int
        Index of the EOD.
        ('N' component of the file name if present).
        -1 if not present in `file_path`.
    ext: str
        File extension *without* leading period
        ('EXT' component of the file name).

    """
    file_path = Path(file_path)
    ext = file_path.suffix
    ext = ext[1:]
    parts = file_path.stem.split('-')
    index = -1
    if len(parts) > 0 and parts[-1].isdigit():
        index = int(parts[-1])
        parts = parts[:-1]
    ftype = ''
    if len(parts) > 0:
        ftype = parts[-1]
        parts = parts[:-1]
    base_path = file_path.parent / '-'.join(parts)
    time = None
    if len(parts) > 0 and len(parts[-1]) > 0 and \
       parts[-1][0] == 't' and parts[-1][-1] == 's' and \
       parts[-1][1:-1].isdigit():
        time = float(parts[-1][1:-1])
        parts = parts[:-1]
    channel = -1
    if len(parts) > 0 and len(parts[-1]) > 0 and \
       parts[-1][0] == 'c' and parts[-1][1:].isdigit():
        channel = int(parts[-1][1:])
        parts = parts[:-1]
    recording = '-'.join(parts)
    return recording, base_path, channel, time, ftype, index, ext


def open_from_zip(file_handle):
    """Open file from corresponding zip file.
    
    Helper function used by the various load_*() functions
    in the waveanalysis and pulseanalysis modules.

    Parameters
    ----------
    file_handle: str, Path, or stream
        The file to be opened for reading.
        If str or Path and file does not exist, try to open
        possible corresponding zip file for reading.

    Returns
    -------
    file_handle: str, Path, or stream
        The file to be read. If not a stream (e.g. does not have a
        readline() function), it still needs to be opened.
        If it is a stream from a zip file (`zf` is not None) it needs
        to be closed after the file has been read.
    zf: ZipFile or None
        If zip file was found and opened, this is the zip file handler
        that needs to be closed after the file has been read.
    """
    zf = None
    if not hasattr(file_handle, 'readline') and not Path(file_handle).is_file():
        _, base_path, _, _, _, _, _ = parse_filename(file_handle)
        zip_file = base_path.with_suffix('.zip')
        if zip_file.is_file():
            zf = ZipFile(zip_file, 'r')
            file_pathes = zf.namelist()
            if file_handle in file_pathes:
                file_handle = io.TextIOWrapper(zf.open(file_handle, 'r'))
            else:
                raise FileNotFoundError(f'"{file_handle}" is not contained in zip-file "{zip_file}"')
        else:
            raise FileNotFoundError(f'neither "{file_handle}" nor "{zip_file}" do existis')
    return file_handle, zf


def close_zip(file_handle, zf):
    """Close stream and corresponding zip file.

    Helper function used by the various load_*() functions
    in the waveanalysis and pulseanalysis modules.

    Parameters
    ----------
    file_handle: str, Path, or stream
        If it is a stream from a zip file (`zf` is not None)
        it is closed.
    zf: ZipFile or None
        If non None, this zip file is closed.
    """
    if zf is not None:
        file_handle.close()
        zf.close()

