name: Build Documentation and Deploy
on: [push]

jobs:
  build-doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: Install dependencies
        run: |
          sudo apt install -y libblas-dev liblapack-dev gfortran libsndfile1 libsndfile1-dev libffi-dev libasound2-dev
          python -m pip install --upgrade pip
          pip install pdoc3
          pip install markdown-include
          pip install mkdocs
          pip install -r requirements.txt

      - name: Install and Build
        run: |
          ./build-docs.sh

#jobs:
#  build-and-deploy:
#    ....
#      - name: Deploy
#        uses: JamesIves/github-pages-deploy-action@v4.2.2
#        with:
#          branch: gh-pages # The branch the action should deploy to.
#          folder: build # The folder the action should deploy.
